### ISSUE TITLE
error in process sentinel: restclient-http-handle-response: peculiar error: "failed with code 22

### ISSUE THREAD

**Issue by localredhead** [pashky/restclient.el#100]
Sorry to bother, but I recently updated all my packages and find I can't use restclient anymore.

This is from my *Messages* buffer.  I hope this is enough information to help determine the cause.

Request being made by restclient:
```
HTTP GET http://localhost:3000/portalapi/countries Headers:[((Content-Type . application/json))] Body:[{
  "document_id": "doc55f745df05f44",
  "token": "ses69e9fe7aef3f8b1eb00c1ced68c23d09f05b7380ed2531fbdc1b025fdaa5a395"
}
]
```
The response I get:
```
Contacting host: localhost:3000
error in process sentinel: restclient-http-handle-response: peculiar error: "failed with code 22
", :host, "localhost", :service, 3000
```

I believe this is a valid request because if I copy the CURL to clipboard and run it the request succeeds.  Any idea what is going on here?

**Comment by pashky** [comment]
#43 ?

**Comment by greenonion** [comment]
@pashky just encountered this as well (code 22). I can confirm that changing localhost to 127.0.0.1 mitigates the problem. Maybe add it to the "Known issues" section of the readme?

**Comment by pashky** [comment]
Please do, I'll merge it :)

**Comment by greenonion** [comment]
Done :)
