### ISSUE TITLE
Tag stable version for MELPA stable

### ISSUE THREAD

**Issue by lvillani** [pashky/restclient.el#104]
Hi there,

Would you consider creating a tag (such as "v1.0.0" or "1.0.0") so that MELPA Stable picks it up automatically?

Thanks!

**Comment by NicolasPetton** [comment]
That would indeed be great!

**Comment by pashky** [comment]
Why do you need this?

**Comment by lvillani** [comment]
MELPA Stable will only pick up repos with tags that correspond to "released" versions of a particular library/software.

**Comment by pashky** [comment]
It doesn't answer my question. So why would you need MELPA Stable?

**Comment by lvillani** [comment]
[MELPA Stable](http://stable.melpa.org/) is the new younger sibling of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be super cool if restclient could be installed via Stable.

Fortunately it's also really easy to support—all you have to do is define a tag in the \`v...\` format and you're done. I'd submit a PR if I could, but since tags are global to a project, that's not something possible via PR.

Thanks for your time and consideration!

**Comment by pashky** [comment]
The thing is that there's no "stable" version of this package, no release process, and no version numbers. And every commit indeed comprises a new release. But feel free to fork it to maintain the list of tags for commits you deem stable if you think there's any value in it.

**Comment by lvillani** [comment]
I see your point. i guess that I'll have to wait until Emacs 25 when package.el gains the ability to set priorities on multiple package archives so that I can mix and match MELPA and MELPA Stable.
