### ISSUE TITLE
Standardize variable handling with vim-http-client

### ISSUE THREAD

**Issue by lakshmivyas** [pashky/restclient.el#110]
[vim http client](
https://github.com/aquach/vim-http-client) is restclient in vim land except for some minor differences.
If those differences are ironed out, the same file can be used by vim and emacs users in a team.

1) I like the simplicity of variable declarations in restclient
2) I like the way file uploads are handled in vim-http-client

**Comment by pashky** [comment]
The implementation of variables is quite different. I have no intent to implement local/global difference, so I guess it's not going to happen.

File uploads may happen in restclient eventually, but I had no need for them yet.

**Comment by lakshmivyas** [comment]
@pashky -  Thanks for the response.  Yes, variable handling in `restclient` is perfect.  It'd be nice if `vim-http-client` adopted it.
