### ISSUE TITLE
 custom definition of the default parameter(s)

### ISSUE THREAD

**Issue by romankrv** [pashky/restclient.el#114]
I needs to custom definition of the default parameter.
For exemple:
#VAR DEFAULTS
Content-Type: application/json 

And then I have more clear my code. Really good idea.

Could you please to do make it? 

Thanking you

**Comment by darrylhebbes** [comment]
Why don't you code it yourself, then submit a pull request?
Its fun learning Lisp.

**Comment by romankrv** [comment]
Darry, do you think that my propose is brilliant idea?

**Comment by localredhead** [comment]
Besides content-type, what other defaults would there be?

**Comment by romankrv** [comment]
Well, it's a 
Authorization: Bearer :TOKEN

Mach the various can be if you are smart

**Comment by pashky** [comment]
@localredhead oh, you never know. My current work's web service requires same 5 custom headers for each request. I'm almost fed up with copying and pasting them. Almost :)

**Comment by romankrv** [comment]
Anyway, even if we're doing default parameter like 'content-type' we improve our code, I know.
This is brilliant idea with a default parameter.

**Comment by pashky** [comment]
Ok, see updates in the above commit. It should help to avoid duplication.
README and httpbin example explain what has changed, please take your time to read and understand how it works. 

As usual it was very briefly tested, so expect bugs and crashes.

**Comment by romankrv** [comment]
Now, I test your update. 
It works prefect! 

Good job.
