### ISSUE TITLE
Allow custom json formatter

### ISSUE THREAD

**Issue by sanel** [pashky/restclient.el#120]
I'm using Emacs 24.3.1 and `json-pretty-print-buffer` doesn't work for me, especially for larger JSON replies, so I went with [json-reformat](https://gist.github.com/gongo/1789605). It would be nice if `restclient.el` could provide a hook for custom formatter or similar solution.

From logs, I've noticed this `json-reformat` was advertised before and removed from README. Why?

**Comment by pashky** [comment]
I have no intent to support any emacs releases older than current stable one and json-pretty-print-buffer works quite well there without need for external dependencies, which is good. 

So it's up to you really, I'd gladly accept PR with such customisable hook, but built-in one will stay as default.
