### ISSUE TITLE
POSTs contain no body

### ISSUE THREAD

**Issue by dncohen** [pashky/restclient.el#121]
I've been a happy user of restclient for a while now.  It's been great.

Unfortunately, I ran a `brew update emacs` on my mac.  Ever since, the body of POSTs never makes it to the server.  I'm looking for help how to troubleshoot this.

I've reinstalled emacs a few times.  Re-installed restclient from MELPA and now trying it straight from this git repo.

Here's how I'm attempting to POST:

```
POST :rc1/oauth/token
Authorization: :basic-auth
Content-Type: application/json

{"grant_type": "client_credentials"}

```

And here's what I see in *messages*, indicating that restclient is treating the body as a header:

```
HTTP POST https://example.com/oauth/token Headers:[(({"grant_type" . "client_credentials"}) (
{"grant_type" . "client_credentials"}) (Content-Type . application/json) (Authorization . Basic xxxxxxxxxxxxxxxxx))] Body:[]
```

**Comment by dncohen** [comment]
I find that if I place a space in the otherwise blank line between headers and body, the request is made properly.
It's a little tricky to be sure the space is always there.  I'd still like a better fix for this.  Before the upgrade, the space was not needed.

**Comment by pashky** [comment]
Wow, nice catch. Please check update.

Thanks.

**Comment by dncohen** [comment]
A belated thanks for the fix!
