### ISSUE TITLE
Request / Question: Option to prevent response buffer from appearing 

### ISSUE THREAD

**Issue by Xeijin** [pashky/restclient.el#122]
I know you can run a query and keep focus in the same window, but what if you don't want to see the response at all?

I want to use restclient.el to post to an internal notification service we have at work (eg when an org-mode task is due, or to send a notification to someone else in the company)

**Comment by pashky** [comment]
What you describe sounds like a repeatable task with a single API call that won't really change much, so you won't get any benefits from restclient's features like variables and both request and response syntax highlighting. 

Thus, putting a elisp function into your configs just for that purpose could be easier and will work faster. You can use something like this https://github.com/tkf/emacs-request to avoid wrestling with url-retrieve monstrous call protocol.

Another option would be to use org-babel. When you put it like this:
```
#+BEGIN_SRC restclient :results silent
POST http://whatever
...
#+END_SRC
```
It will flick response briefly in minibuffer and then ignore it.

**Comment by Xeijin** [comment]
Thanks, I seem to be struggling a bit with request.el and the documentation isnt providing the answer...

I have a pretty-print JSON that looks something like this:

```
{

     "parameters" : {
                     "item 1": "value 1",
                     "item 2": "value 2",
                     "item 3": "value 3"
                              }
}
```

As you can see, the key-value pairs are nested within the "paramaters" array.

How do I represent this using request.el? Doing the following (based on an example in documentation) gives me an integerp error / lisp syntax errors...

```
(request
    "<url>"
:type "POST"
:data '(("parameters" . (("item 1" . "value 1"
                                      ("item 2" . "value 2")
                                      ("item 3" . "value 3")))
:parser 'json-read)
```

**Comment by pashky** [comment]
@Xeijin to be honest, I don't use request.el that much myself, yet I'm considering to use it as a possible back-end for restclient.el, so I played with it a bit.

I think you need to do something like this:
```
:data (json-encode '(("parameters"  ("item 1" . "value 1")
                                      ("item 2" . "value 2")
                                      ("item 3" . "value 3"))))
```

I've also found earlier that a snippet like this works too:
```
(request
 "http://httpbin.org/post"
 :type "POST"
 :data "{ \"some\": \"json\" }"
 :parser 'buffer-string
 :complete (cl-function (lambda (&key response &allow-other-keys)
                          (message "Headers %s\nBody %s" (request-response--raw-header response)  (request-response-data response)))))
```

You obviously don't need `:complete` function.

**Comment by Xeijin** [comment]
Thanks @pashky  that works great! 

This was what the skeleton of my code ended up looking like for anyone interested (note an extra set of enclosing parenthesisfor the "parameters" structure):

```
(request
"http://httpbin.org/post"
:type "POST"
:data (json-encode `(("parameters" . (        ; Prepend alist structure with a backtick (`) rather than single quote (') to allow evaluation of elisp functions by prefixing them with a comma (,)
                                   ("item 1" . "value 1")
                                   ("item 2" . t) ;this value is expected as a boolean so use the nil / t denotation as this is an emacs alist structure
                                   ("item 3" . ,(your-custom-elisp-function))))) ; The function will be evaluated as it has been prefixed with a comma (,)
:parser 'buffer-string)
```
