### ISSUE TITLE
I can't emit Accepted: application/json in headers

### ISSUE THREAD

**Issue by turbopape** [pashky/restclient.el#126]
hi,
When I query a hbase REST endpoint:
GET http://master2:9999/somedb/schema
Accepted: application/json

I get the "text/plain" response. If I do it from curl -H "Accepted: application/json" it works.

Any Idea ?

Thank you !

**Comment by alexey-martynov** [comment]
According to RFC 2616 (https://www.ietf.org/rfc/rfc2616.txt) it should be "Accept" header. Look at section 14.1
