### ISSUE TITLE
uppercase/lowercase variables

### ISSUE THREAD

**Issue by humitos** [pashky/restclient.el#128]
Hi, thanks for this amazing emacs mode :)

That said, I want to report something that for me is a bug: when naming a variable uppercase the content of it is sent in uppercase, and when naming the variable lowercase the content is sent as it is (without modification).

I'm not an emacs lisp developer, but I tried to found the why and I couldn't)

I will show an example:

Lowercase variable naming:
```
:auth_token = $1$15n4/WxP$NtDV3L9-ycKy0EeFCH7qLR1
GET http://httpbin.org/headers
Authorization: Bearer :auth_token
```

HTTP Response shows:
```
{
  "headers": {
    "Mime-Version": "1.0",
    "Host": "httpbin.org",
    "Extension": "Security/Digest Security/SSL",
    "Content-Length": "0",
    "Authorization": "Bearer $1$15n4/WxP$NtDV3L9-ycKy0EeFCH7qLR1",
...
```

Uppercase variable naming:
```
:AUTH_TOKEN = $1$15n4/WxP$NtDV3L9-ycKy0EeFCH7qLR1
GET http://httpbin.org/headers
Authorization: Bearer :AUTH_TOKEN
```

HTTP Response shows:
```
{
  "headers": {
    "Mime-Version": "1.0",
    "Host": "httpbin.org",
    "Extension": "Security/Digest Security/SSL",
    "Content-Length": "0",
    "Authorization": "Bearer $1$15N4/WXP$NTDV3L9-YCKY0EEFCH7QLR1",
...
```

Voalá ;)

Do you have a clue about what's happening?

**Comment by pashky** [comment]
Oh yeah, I sure do know. Sorry for that!

**Comment by humitos** [comment]
Niiice! Thanks a lot! :D
