### ISSUE TITLE
Installation error: Scan error: "Unbalanced parentheses"

### ISSUE THREAD

**Issue by nodo** [pashky/restclient.el#130]
Hi,

when trying to install `restclient` I get the following error:
```
Making version-control local to restclient-autoloads.el while let-bound!
Generating autoloads for restclient.el...
forward-sexp: Scan error: "Unbalanced parentheses", 20260, 20481
```

I am getting the error using `emacs -q` as well as using my config. Do you have any idea?

I am using Emacs `24.5.1` installed using homebrew.

Thanks!
Andrea

**Comment by pashky** [comment]
Melpa serves truncated file. Please report issue there or use source from this repo directly.
