### ISSUE TITLE
Error POSTing an XML when opening element is not closed on the same line

### ISSUE THREAD

**Issue by razzmatazz** [pashky/restclient.el#132]
running something like

```
<?xml version="1.0" encoding="utf-8"?>
<AAA xmlns="ns"
     another-attr="x">
</AAA>
```

triggers a an error:
```
restclient-read-file: Opening input file: No such file or directory, /Users/username/AAA xmlns="ns"
```

Keeping `another-attr=` on the same line as opening `<AAA` will work

**Comment by pashky** [comment]
thanks for spotting, please check if update works for you

**Comment by razzmatazz** [comment]
@pashky – works fine now;
and thanks for all the work done on restclient, love it
