### ISSUE TITLE
Define new minor mode for the response buffer

### ISSUE THREAD

**Issue by gaudecker** [pashky/restclient.el#137]
My specific use-case would be to bind the key <kbd>q</kbd> to delete the window just like in `*Help*` and others.

**Comment by pashky** [comment]
try putting `(local-set-key "q" '(lambda () (interactive) (quit-window t)))` in `restclient-response-loaded-hook` perhaps?

**Comment by gaudecker** [comment]
Ah so that's the hook I was missing! I just tested and it works. Thank you!

**Comment by pashky** [comment]
@gaudecker cool! though minor mode sounds like a good idea indeed. i may add this when i have some free time.
