### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by falood** [pashky/restclient.el#144]
![image](https://cloud.githubusercontent.com/assets/184053/20609656/46b7887c-b244-11e6-9c74-e58cc6886de3.png)
Failed to post unicode character.

Maybe `中文` is useful for you to debug.

**Comment by sukeyisme** [comment]
http://blog.somof.net/?p=1310
http://www.cnblogs.com/yangwen0228/p/6238723.html
FYR, not restclient.el 's problem

**Comment by falood** [comment]
Thanks, I'll check these links ♥
