### ISSUE TITLE
Basic access authentication for requests

### ISSUE THREAD

**Issue by jonkri** [pashky/restclient.el#15]
Hi, and thanks for this nice Emacs extension!

I would just like to let you know that I would have liked to see restclient.el support for handling authentication for requests in the form of http://username@example.com/. No password would necessary for me, but  that would of course be nice to have too. :-)

Thanks for whatever you can do!

**Comment by c0b** [comment]
@pashky the preferred way would be save in variable, like this seems not supported yet? I got an error on the line of `base64-encode-string` it seems cannot reference the variables defined?

```
:user = username-could-be-very-long
:pass = password-may-also-be-very-long-with-all-kinds-of-weird-characters
:auth_basic := (base64-encode-string (format "%s:%s" :user :pass) t)

Authentication: Basic :auth_basic
```

thanks;

**Comment by nitishch** [comment]
@c0b The problem in your example seems to be that you are using _restclient_ variables in an elisp form. I didn't find any such usage in `examples/httpbin`. This might not be supported yet.

**Comment by nitishch** [comment]
@c0b Yes, it appears that the restclient variables cannot be used in an elisp form. I was looking at the code and it seems supporting this needs only small changes. @pashky Is this deliberately not implemented?

**Comment by dl1ely** [comment]
For the people coming here to find out how to do the basic authentication with restclient.el, the HTTP header field is `Authorization`, **not** `Authentication` as stated multiple times.

**Comment by hornuda** [comment]
@pashky: First of all - this one is very useful plugin - thank you!Above you mentioned digest auth doesn't work right now. Are there any plans to support digest auth?

**Comment by pashky** [comment]
@hornuda In a user-friendly way - no. Nothing stops you from doing the auth flow manually, though, copy-pasting chanllenges and encoding responses.
Or you can deactivate `url-http-handle-authentication` advice and url.el will ask for credentials as normal, if you were accessing website.
