### ISSUE TITLE
Posting JSON with non-ascii characters fails

### ISSUE THREAD

**Issue by etu** [pashky/restclient.el#156]
Example below:
```
POST https://example.com/
Content-Type: Application/Json

[
  {
    "name": "Räksmörgås"
  }
]
```

All the letters in the json is valid json.

The error I get is:
```
error in process sentinel: Multibyte text in HTTP request:
[... info about request ...]
```

**Comment by chuan-su** [comment]
+1

**Comment by pashky** [comment]
It was working before just fine. Seems that around emacs 25.x something has changed internally.

**Comment by etu** [comment]
That would't surprise me if it has been working since I've been using this plugin for years and years, both for work and private usage. And as a swede, at a swedish company. You tend to end up with non-ascii characters from time to time... :)

**Comment by pashky** [comment]
I'm not exactly ASCII-native myself, so I even had a test in examples just for that :)

So there's something of interest here https://github.com/proofit404/anaconda-mode/issues/189
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24117

From brief scanning I got the idea what's wrong, but didn't quite understand if I can do anything to avoid it and what it would be. And it seems that they fixed something in url.el in the end, but I'm not sure if it has trickled into emacs release already. I'll try to find time to figure all of that out later this week, I guess.

**Comment by pashky** [comment]
I think I fixed it. Please update and let me know if it works.

**Comment by etu** [comment]
Nice! Just updated it from melpa and tested my example above :)

Thanks @pashky 👍
