### ISSUE TITLE
text/plain body with no newlines cuts off last characters.

### ISSUE THREAD

**Issue by Pitometsu** [pashky/restclient.el#157]
```
#
# example request
#
GET http://0.0.0.0:8083/v1/token?hash=0eee49780d215d56da8b77adc662da73&key=1024
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
```
And response:
```
7689
// GET http://0.0.0.0:8083/v1/token?hash=0eee49780d215d56da8b77adc662da73&key=1024
// HTTP/1.1 200 OK
// Content-Type: text/plain
// Connection: Keep-Alive
// Content-Length: 32
// Request duration: 0.113371s
```
But original body was:
`7689c2f61f62c7789ddd8a521da7dda5`

**Comment by Pitometsu** [comment]
FYI: just for a moment after response arrived, all the body displayed in `*HTTP Response*` buffer, without any comments, but then it replaced with cutted body with comments.

**Comment by pashky** [comment]
nice find. should be fixed now, but will break again if response doesn't contain actual text/plain content-type

body is assumed to be json by default (because in most cases nowdays it is) and json-pretty-print silently deletes something it cannot understand as valid json (as in your token)

**Comment by Pitometsu** [comment]
@pashky well, actually, even text/plain _must_ end with \r\n, but occasionally it just not. Thank you for fix!

**Comment by pashky** [comment]
End of line doesn't matter here really. Copy/paste your example token value into empty buffer (any mode), run json-pretty-print-buffer and see what happens. Then try adding a few numbers before first c and try again :)
