### ISSUE TITLE
Variable is not used

### ISSUE THREAD

**Issue by ulrivo** [pashky/restclient.el#159]
Hi,

if I submit

`
:cookie=ulrich

GET https://api.github.com
Cookie: :cookie
`

everything works as expected, i. e. the variable cookie is used. The log says:

`
HTTP GET https://api.github.com Headers:[((Cookie . ulrich))] Body:[]
`

But if I have a different value for cookie like

`
:cookie=B=db9s6bpclha4g&b=3&s=eq

GET https://api.github.com
Cookie: :cookie
`
the variable cookie is not used:

`
HTTP GET https://api.github.com Headers:[((Cookie . :cookie))] Body:[]
`

Any suggestion?

Regards,
Ulrich

**Comment by pashky** [comment]
Suggestion 1: My variable parser is shite :)

Suggestion 2: try using := syntax as workaround it may work, and I'll have a look why it's not picking it up when I'm back to computer.

**Comment by ulrivo** [comment]
Using := and enclosing ' works:
`
:cookie:='B=db9s6bpclha4g&b=3&s=eq'

GET https://api.github.com
Cookie: :cookie
`

**Comment by pashky** [comment]
Please update. Var regexp wasn't well thought through indeed.
