### ISSUE TITLE
In-buffer variables

### ISSUE THREAD

**Issue by magnars** [pashky/restclient.el#16]
Hello!

Thanks for createing restclient.el, I find it absolutely excellent. I love the simplicity, and I can't think of a better API for exploring services.

Here's an idea: What if I could declare some variables (like maybe some ID, or Cookies), and then it would be interpolated into the request before calling?

Something like this:

```
:event-id = 83641034
:missive-id = 343

# Get sent-status for an event and a missive
GET http://localhost:4005/events/:event-id/missives/sent-status/:missive-id
```

I would be happy to give it a go, if you would accept a pull request for something like this. :)

**Comment by arialdomartini** [comment]
(10 years late) thank you @magnars for adding variables support to restclient.

In the rare cases where the boundaries of a variable are not clear, such as in

    :prefix = foo
    GET https://example.com/api?search=:prefixbar

I use to do define instead

    :{prefix} = foo
    GET https://example.com/api?search=:{prefix}bar


I just wonder if you originally had in mind a different approach.
