### ISSUE TITLE
Passing curl options. Example: -k

### ISSUE THREAD

**Issue by vharish** [pashky/restclient.el#174]
Hi,

I have a dev server with our own certificate. I am not quite sure how it was generated.
However, when I am making a get request, restclient gives an error saying: `The x509 certificate does not match`.

Now, there is an option in curl(-k) to turn off certificate verification. Giving this option works fine through command line. My question is, how can I pass the option in restclient? Is it supported?

[Stockoverflow](https://stackoverflow.com/questions/20842970/fix-curl-51-ssl-error-no-alternative-certificate-subject-name-matches) Reference

**Comment by pashky** [comment]
restclient.el doesn't use curl at all, so it very much depends on how TLS is configured in your emacs

it gives you interactive warning and asks if you want to trust the cert, if emacs is compiled with gnutls. so i suggest you to use gnutls..

**Comment by vharish** [comment]
Ok. Thank you.
