### ISSUE TITLE
A way to apply arbitrary Lisp to the data returning from a query?

### ISSUE THREAD

**Issue by jwiegley** [pashky/restclient.el#177]
Sometimes I want to filter the results of an another too large query, like un-gzipping and un-taring a specific file from some binary tarball response, and filtering what is reported from that file down to a certain number of lines.  On the command-line I do something in the spirit of this:

```
curl | jq '.field' | base64 -d | tar xvJf - output.log | grep -i error
```

All of this can be done within Emacs, of course, either using Lisp or running shell commands to filter the buffer contents. Perhaps restclient.el could allow for a pseudo-tag in the query that allows a Lisp form to be run in the temporary buffer containing the response data?

**Comment by pashky** [comment]
Well, there's a post-response pre-format hook, of course. But no, it's not a good answer. 

The truth is that I tried to come up with good syntax for per request custom processing in the early days of this project, but failed. Your example is a little extreme, I only had stuff like capturing auth tokens in mind, but the principle ought to be generic enough to allow both. Even if I did come up with a syntax, that naïve regex-based parser is stretched beyond maintainability already, and editing is another headache, I'm no @fxbois to tackle nested syntaxes properly.

Anyway, have you thought how it might look like? Something similar to variables, I presume, just a piece of code to run on a raw response buffer?

**Comment by pashky** [comment]
Trickling parsed request down to https://github.com/pashky/restclient.el/blob/master/restclient.el#L301 is the only missing bit preventing to implement this as a hook. Would you mind to try and do a PR if it works for you?

**Comment by pashky** [comment]
Fair enough

**Comment by nitishch** [comment]
>  Would you mind to try and do a PR if it works for you?
@pashky did you mean PR for adding a header as suggested by @jwiegley? If yes, I can have a go at it.
