### ISSUE TITLE
C-c C-c with multiple POST in buffer does not work

### ISSUE THREAD

**Issue by n1zea144** [pashky/restclient.el#182]
Its seem that "C-c C-c: runs the query under the cursor, tries to pretty-print the response (if possible)"
does not work when multiple POST are in buffer.  Unless I comment out previous POST, I get "Bad Request" response by http server.  Unless I add a '#' before POST https://some/request/one, the POST https://some/request/two cannot be completed.

POST https://some/request/one
accept: ...
{
...
}

POST https://some/request/two
content
{
...
}

**Comment by pashky** [comment]
It's not supposed too. https://github.com/pashky/restclient.el#usage
