### ISSUE TITLE
Is it possible to capture response body in a variable?

### ISSUE THREAD

**Issue by n1zea144** [pashky/restclient.el#183]
I'm testing a password protected web service and I first have to authenticate, obtain a token, and then make subsequent POST requests.  Is it possible to save a property from the returned json and use that in a subsequent header?

POST /authenticate/token
{
...
}

returns:

{
"auth_token" : "XXXX"
}

use token in next POST:

POST /data
Authorization: Bearer XXXX
{
...
}

**Comment by pashky** [comment]
#149
