### ISSUE TITLE
after restclient-narrow-to-current, how to restore the original full buffer content?

### ISSUE THREAD

**Issue by c0b** [pashky/restclient.el#196]
my buffer has 3 sections of content, after `C-c n n (restclient-narrow-to-current)` applied, it shows only 1 section, and killed the others,  my question is there anyway to restore the original full buffer content? I have tried the `C-x u` to undo the changes but not working

    # comment
    POST http://.../api/action1
    
    # comment2
    POST http://.../api/action2
    
    # comment2
    GET http://.../api/action3

I wonder: after `C-c n n (restclient-narrow-to-current)` applied, is everything else in the buffer permanently lost?

**Comment by pashky** [comment]
https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html

**Comment by c0b** [comment]
so would you mind to mention the link in the doc, or in code comment; to give someone (who has never used the narrowing feature) the chance how to restore the whole buffer

**Comment by pashky** [comment]
I do mind. I assume one should learn basic emacs functions before you use extensions, not other way around.
