### ISSUE TITLE
Could I set a default host or a variable of host?

### ISSUE THREAD

**Issue by liuchong** [pashky/restclient.el#198]
I would request many path from a single host such as example1.com, or sometimes change to example2.com, is there a simple way to switch between them different hosts?

Such as set a default host of whole file, or use a variable to represent it, instead of replace "example1.com" to "example2.com" in whole file?

**Comment by dakra** [comment]
If you're asking about the `Host` header, then no, see https://github.com/pashky/restclient.el/issues/154
For the hostname in the url you can just use a variable.

**Comment by liuchong** [comment]
Thanks, in the url. But how could I set a variable in url?

**Comment by liuchong** [comment]
Thanks, it's solved with:
```
# variables
:HOST := "localhost"
:PORT := "8180"
#

# ping
GET http://:HOST::PORT/ping
```
