### ISSUE TITLE
failed to define function rest client error on load

### ISSUE THREAD

**Issue by chadhs** [pashky/restclient.el#209]
```
File mode specification error: (error Autoloading file ~/.emacs.d/elpa/restclient-20190405.2008/restclient.elc failed to define function rest client)
```

When open a rest.http file in a project I get the above error.  
The same error occurs when I press `M-x` and manually activate restclient.

I tried removing and reinstalling the package as well.

I'm running the current Emacs 26.2 release that came out recently.

Let me know what other information I can provide.  Thank you.

**Comment by chadhs** [comment]
inserting this at the top of the file, killing the buffer, then opening the file does allow rest client to load.
```
-*- mode: restclient -*-
```

**Comment by ttych** [comment]
Another solution if you want to associate .http extension to restclient-mode is to have this in your dot-emacs file : 

`(use-package restclient
  :ensure t
  :mode (("\\.http\\'" . restclient-mode)))`

**Comment by chadhs** [comment]
I had `:mode ("\\.http\\'")` which wasn't correct, and since I was relying on :mode I wasn't able to load the package.  I feel like this worked in the past, but probably not??  Closing this; thanks for help!
