### ISSUE TITLE
Org-mode integration

### ISSUE THREAD

**Issue by novoid** [pashky/restclient.el#21]
Hi!

This is a feature request:

Have you ever considered to create the glue that it is possible to integrate restclient.el into Org-mode?

It would be pretty cool to C-c C-c on following line ...
```
#+BEGIN_SRC REST
GET http://myserver/rest/dothis
Authorization: Basic YmVfcmVzdF9hZG1
Accept-Encoding: application/xml
#+END_SRC
```
... and get the XML response like this:
```
#+RESULTS:
: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
: <faultInfo xmlns="http://example.com/product/model">
:   <...>
: </faultInfo>
```

I am no ELISP programmer but I guess this feature is not much of a work for someone who is also familiar with Org-mode ...

**Comment by stardiviner** [comment]
Org-mode integration is really great.

**Comment by squiter** [comment]
This type of integration must be created in [Babel](http://orgmode.org/worg/org-contrib/babel/).  
I'm not a lisp programmer, but if someone will try to create it you can use [this template.](http://orgmode.org/w/worg.git/blob/HEAD:/org-contrib/babel/ob-template.el). :)  
This integration is an awesome idea! :)

**Comment by stardiviner** [comment]
I found similar one: https://github.com/zweifisch/ob-http
And I'm a little familiar with elisp, I'm tring to modify the ob-template.el and ob-http. to put them together.

**Comment by alf** [comment]
I've got a simple integration working. I'll clean it up and send a PR tomorrow.

**Comment by alf** [comment]
I've added a very basic solution at #92.

**Comment by stardiviner** [comment]
great to see the progress.

**Comment by manandbytes** [comment]
I tnink it makes sense to accept initial implementation from #92 as part of restclient.el itself. WDYT?

**Comment by pashky** [comment]
I'd rather not. I believe it's better to release it as a separate package, then feel free to link it in restclient's README for better visibility, I'd accept such PR straight away.

**Comment by alf** [comment]
I'll get to this tomorrow.

**Comment by alf** [comment]
Sorry for the delay, it's [out](https://github.com/alf/ob-restclient.el) now. Thus we can close this issue.

Feature requests for the org-mode integration should be created [here](https://github.com/alf/ob-restclient.el/issues).

**Comment by manandbytes** [comment]
:thumbsup:

**Comment by novoid** [comment]
Thanks very much for the effort!
