### ISSUE TITLE
restclient treats variable definition as part of payload

### ISSUE THREAD

**Issue by shanavas786** [pashky/restclient.el#216]
```
GET http://server/path
Content-Type: application/json
{
  "key": value
}

:var := myvalue
```
treats `:var := myvalue` as part of payload
![restclient](https://user-images.githubusercontent.com/5337197/60024172-edd5c400-96b4-11e9-87c9-c57c8f419c1d.png)

**Comment by pashky** [comment]
please read the doc carefully regarding query delimiters
