### ISSUE TITLE
Melpa recipe outdated?

### ISSUE THREAD

**Issue by jgerman** [pashky/restclient.el#238]
Is the Melpa recipe out of date?

```
(restclient :repo "pashky/restclient.el"
            :fetcher github
            :files ("restclient.el"))
```

Since the recipe only specifies restclient.el we don't get `jq` and `helm` from melpa right?

**Comment by pashky** [comment]
I’ve never bothered to learn how melpa actually works. Is it some repo one needs to submit a PR against? Someone else probably added this recipe before recent additions. If so, feel free to update it.

**Comment by jgerman** [comment]
I don't honestly know myself, this is the first time I've actually looked at a recipe ;)

I'll take a look when I have time and submit a PR.

**Comment by jgerman** [comment]
I submitted a PR up to melpa, it worked for me locally manually building and installing from my cloned melpa. restclient-helm was already there, so I just added jq. 

PR is here: https://github.com/melpa/melpa/pull/6981

**Comment by pashky** [comment]
Thank you!
