### ISSUE TITLE
Unknown restclient hook type jq-set-var

### ISSUE THREAD

**Issue by jadler** [pashky/restclient.el#240]
I've installed restclient theses days and try to execute:

    :header = <<
    Content-Type: application/json
    Accept: application/json
    User-Agent: Emacs Restclient
    #
    
    # same thing with jq if it's installed
    GET http://httpbin.org/ip
    :header
    -> jq-set-var :my-ip .origin

And I received  the "Unknown restclient hook type jq-set-var" message in the echo area.

The restclient installed version is 20200502.831

**Comment by dassburger** [comment]
Requires a separate package, `restclient-jq` to be installed. It is not in MELPA at the moment. I have created a pull request to add it: https://github.com/melpa/melpa/pull/7100

**Comment by jadler** [comment]
Thanks for the reply, I will wait for the package to be released on MELPA.

**Comment by snowman** [comment]
The file `restclient-jq.el` is on the same repos as https://github.com/pashky/restclient.el. 😃
