### ISSUE TITLE
restclient-elisp-result-function: Invalid function: (form (macroexpand-all (read (current-buffer))))

### ISSUE THREAD

**Issue by snowman** [pashky/restclient.el#248]
when running from example:

```bash
# set a variable :my-ip to the value of your ip address using elisp evaluated in the result buffer
GET http://httpbin.org/ip
-> run-hook (restclient-set-var ":my-ip" (cdr (assq 'origin (json-read))))
```

**Comment by vritser** [comment]
same error

**Comment by vritser** [comment]
I had fixed this: add `(require 'cl)` to restclient.el, then recompile it

**Comment by snowman** [comment]
thanks, it works!

**Comment by fstamour** [comment]
I had a very similar code (a `POST` instead of a `GET`, same "hook", etc) with a slightly different error message: `restclient-parse-hook: Invalid function: (handler (assoc cb-type restclient-result-handlers))`

@vritser 's fix worked, thanks a lot!
