### ISSUE TITLE
Unknown restclient hook type on-response

### ISSUE THREAD

**Issue by snowman** [pashky/restclient.el#254]
https://github.com/pashky/restclient.el/blob/abc307b965bf6720bc466281f2e204cd5ce37dc3/restclient.el#L565-L570

https://github.com/pashky/restclient.el/blob/abc307b965bf6720bc466281f2e204cd5ce37dc3/examples/httpbin#L34-L38

**Comment by eggcaker** [comment]
should be change to `run-hook (message "another hook")`
