### ISSUE TITLE
Doesn't do anything in Aquamacs

### ISSUE THREAD

**Issue by dragos** [pashky/restclient.el#26]
I successfully installed it in Aquamacs, and I have the `REST Client` mode available (syntax highlighting too). When trying the example in the README, nothing happens when I press C-c C-c (or C-c C-r). The only thing it does is to move the cursor to the top-left corner.

**Comment by MitchellJThomas** [comment]
I'm using Aquamacs 3.2 GNU Emacs 24.4.51.2 and restclient mode works just fine.

**Comment by dragos** [comment]
Latest version is working... closing this.
