### ISSUE TITLE
Not possible to set multiple cookies

### ISSUE THREAD

**Issue by dadinn** [pashky/restclient.el#262]
Specifying multiple Cookie headers doesn't get sent as expected.

# Steps to reproduce

Execute this expression:
```
#testing cookies
GET http://httpbin.org/cookies
Cookie: FOO=BAR
Cookie: BAR=BAZ
```

Returns this:
```
{
  "cookies": {
    "FOO": "BAR,BAR=BAZ"
  }
}

// GET http://httpbin.org/cookies
// HTTP/1.1 200 OK
// Date: Thu, 03 Jun 2021 01:15:44 GMT
// Content-Type: application/json
// Content-Length: 48
// Connection: keep-alive
// Server: gunicorn/19.9.0
// Access-Control-Allow-Origin: *
// Access-Control-Allow-Credentials: true
// Request duration: 2.028843s
```

Expected:
```
{
  "cookies": {
    "FOO": "BAR",
    "BAR": "BAZ"
  }
}
```

I assume something is not working correctly there!
Either the `httpbin.org` service is parsing the cookies wrong, or restclient is sending them wrong.
How it is possible then to specify multiple cookies?

# Bonus points
Also, it is not clear from the documentation, wether restclient collect/keep cookies somewhere?
If so where, and how can this process be controlled?
There is a variable `restclient-inhibit-cookies`, which documentation says "Inhibit restclient from sending cookies implicitly", but it's not clear where these "implicit cookies" come from. In my above examples cookies were defined quite explicit! 

# Versions

OS: Debian Bullseye
Emacs: 27.1
Restclient: `2cc1fd3496f57288de3f97c27a5f018284db2d23`

**Comment by pashky** [comment]
just put them on the same line

**Comment by dadinn** [comment]
What have you tried?
What were your results?

**Comment by dadinn** [comment]
```
#testing cookies
GET http://httpbin.org/cookies Cookie: FOO=BAR Cookie: BAR=BAZ
```

Ah, makes perfect sense! I should have thought of that myself!!!

**Comment by dadinn** [comment]
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

<!-- GET http://httpbin.org/cookies Cookie: FOO=BAR Cookie: BAR=BAZ -->
<!-- HTTP/1.1 404 NOT FOUND -->
<!-- Date: Mon, 07 Jun 2021 17:53:03 GMT -->
<!-- Content-Type: text/html -->
<!-- Content-Length: 233 -->
<!-- Connection: keep-alive -->
<!-- Server: gunicorn/19.9.0 -->
<!-- Access-Control-Allow-Origin: * -->
<!-- Access-Control-Allow-Credentials: true -->
<!-- Request duration: 0.826257s -->
```

Hmm, maybe not... any other suggestions!?

**Comment by pashky** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie

**Comment by dadinn** [comment]
Nice!
