### ISSUE TITLE
Allow the use of elisp expressions to calculate HTTP messages

### ISSUE THREAD

**Issue by abingham** [pashky/restclient.el#37]
On one rest system I'm developing I have to include an HMAC string in each request. This string is calculated using a secret key and the contents of the HTTP message. To use `restclient.el` it would be really useful if I could elisp to calculate that string for me. The alternative is that I do it by hand, and that's pretty tedious.

Conceptually what I want is something like this

```
POST http://127.0.0.1:58681/endpoint
Content-Type: application/json
X-Ycm-Hmac: (base64-encode-string (encode-hex-string (ycmd--hmac-function {{msg-contents}} ycmd--hmac-secret)))

{some: json}
```

I don't know how common this use-case is, but it's almost a show-stopper in some situations.

**Comment by eggcaker** [comment]
so, for now still no way to get body content from elisp code directly ? like want to take a body to calc hmac ?
