### ISSUE TITLE
Re-use displayed *HTTP response* window

### ISSUE THREAD

**Issue by svend** [pashky/restclient.el#42]
I get a new split window each time restclient-http-send-current is run. For example, the first time it is run, there are two windows, the REST buffer, and the reponse window. The second time it is run, the frame gets split again, with the REST buffer, a new response window, and some other buffer. It would be great if the HTTP response window was refreshed if it already displayed, without the frame being split again.

**Comment by osxi** [comment]
@svend, what is the value of your `restclient-same-buffer-response` and `restclient-same-window-response` variables? They should probably be set to `t`.

**Comment by svend** [comment]
@pashky I get the behavior with `emacs -Q`, so I don't think there are any custom settings.

@osxi `restclient-same-buffer-response` is `t`. `restclient-same-window-response` is not defined.

**Comment by svend** [comment]
I get the same behavior with the following elisp, so it looks like this isn't an issue with restclient.

```lisp
(progn
  (when (get-buffer "*test*")
    (kill-buffer "*test*"))
  (get-buffer-create "*test*")
  (display-buffer "*test*" t))
```

**Comment by abingham** [comment]
I'm seeing problems related to responses and windows as well, though it's slightly different than what's described here. When I run `restclient-send-http-current` I don't get new splits, but the response buffer *does* get moved around. That is, if the response buffer was in the upper right and I run the command, it will generally get moved (closed and opened again?) in a new location.

I don't know if this is a symptom of the same defect, so let me know if I should open a new issue.

**Comment by svend** [comment]
@abingham I think the cause is the same. The existing response buffer is killed, and url-retrieve creates a new buffer.

**Comment by BrunoBonacci** [comment]
Hi, I'm experiencing the same behaviour described by @abingham.
Is there any way we can keep the same response buffer in the same place without get it to move on every `C-c C-c`?
Interesting enough this happens only it seems to be happening only in full-screen.
Any guess on how to fix this?

**Comment by pashky** [comment]
@svend try https://github.com/pashky/restclient.el/tree/42_dont_kill_buffer let's see if not killing response buffer helps

**Comment by BrunoBonacci** [comment]
yes, the fix in the branch *42_dont_kill_buffer* seems to be working.
thx @pashky

**Comment by pashky** [comment]
Ok, I'm merging it in then...

**Comment by svend** [comment]
Works for me as well. Thanks!
