### ISSUE TITLE
Perculiar error when GETing localhost:3000

### ISSUE THREAD

**Issue by ghost** [pashky/restclient.el#43]
Firstly, thanks for creating this useful mode for emacs :) 
Regarding the error, I have the error below when I tried to do the get request to `http://localhost:3000` 

```
error in process sentinel: peculiar error: "failed with code 111                                                                       
", :host, "localhost", :service, 3000
```

**Comment by nroose** [comment]
Oh well.  I saw something about restclient in emacs and was excited. My app needs the name, though (I have the name set to go to 127.0.0.1 in my /etc/hosts file), and so this bug prevents me from using restclient in dev. I will use it against our test servers, though.

**Comment by pashky** [comment]
@nroose for ipv4 address it should work. It fails only if localhost points to both ipv4 and ipv6 addresses.

**Comment by nroose** [comment]
Perhaps a different error then?
```
error in process sentinel: peculiar error: "failed with code 22
", :host, "localhost.repairpal.com", :service, 3001
```
I did have
```
::1             localhost
```
in my hosts file, but I don't think I actually use it and now I commented that out, and still get this error.
Thanks.

**Comment by pashky** [comment]
@nroose ok, i don't know really then. do other names not work too? like, "127.0.0.1 myhost" entry?
