### ISSUE TITLE
Use restclient behind proxy

### ISSUE THREAD

**Issue by calve** [pashky/restclient.el#58]
Hi

From my point of view, it looks like restclient does not follow the proxy settings set as environment variables. Inside a proxyfied emacs (ie, I can access to MELPA/marmelade/eww), restclient does not proxyfied the requests it makes.

I, for example, get this error when trying a simple ``POST``

```
HTTP/1.0 500 Internal Server Error
Date: Thu, 22 Jan 2015 16:32:34 GMT
Server: Apache/2.4.6 (Ubuntu)
Content-Length: 21
Content-Type: text/plain
X-Cache: MISS from cacheserv.proxy.fr
Via: 1.1 cacheserv.proxy.fr:3128 (squid/2.7.STABLE5-20081030)
Connection: close

Internal Server Error
```

Let me know if you need more informations

**Comment by pashky** [comment]
Please report this to https://debbugs.gnu.org/Emacs.html as restclient.el uses url.el, which is part of GNU Emacs to make requests.

**Comment by expez** [comment]
@calve are you seeing this through?  I'd also like to be able to use restclient behind the proxy at work.

**Comment by calve** [comment]
I'm afraid I did not move on this issue, since I did not experienced it again. I will post an anwser here if I find one.

**Comment by calve** [comment]
@expez I passed my school proxy with this lisp : 
``(setq url-proxy-services '(("http" . "proxy.example.org:3128")))``

**Comment by expez** [comment]
thanks, @calve!
