### ISSUE TITLE
problems with json-pretty-print-buffer

### ISSUE THREAD

**Issue by jvillasante** [pashky/restclient.el#59]
I'm really new to emacs, as in I've just installed it today. Comming from vim i think modes like this restclient will improve a lot my workflow at work. Here's is my problem.

After pressing C-c C-c here's the error I get: 
error in process filter: Symbol's function definition is void: json-pretty-print-buffer

I'm using emacs24 on ubuntu. Maybe I need some dependencies??

**Comment by pashky** [comment]
You should upgrade to emacs 24.4
