### ISSUE TITLE
Automatically encode HTTP form variables

### ISSUE THREAD

**Issue by groks** [pashky/restclient.el#63]
It would be cool if when we write this:

    GET http://localhost/test
    a=value
    b=space value

it is translated into a request like this:

    GET /test?a=value&b=space+value HTTP/1.1

and if you specify POST:

    POST http://localhost/test
    a=value
    b=space value

the request would is encoded correctly:

    POST /test HTTP/1.1
    Content-Type: application/x-www-form-urlencoded
    
    a=value&b=space+value

**Comment by pashky** [comment]
a := (url-encode-url "what ever")
