### ISSUE TITLE
Entities with UTF-8 chars sometimes fail strangely

### ISSUE THREAD

**Issue by pandeiro** [pashky/restclient.el#68]
I am having a bad time figuring out why and what this is, but here is the simplest reproducible case I can come up with:

OK:
```
PUT http://httpbin.org/put
Content-Type: application/json

{
    "text": "João"
}
```

This will return the httpbin-formatted JSON response that includes this:
```
{
  ...
  "json": {
    "text": "Jo\u00e3o"
  }, 
  ...
}
```

**However**, if you use a payload with a second UTF-8 character, such as this:
```
PUT http://httpbin.org/put
Content-Type: application/json

{
    "text": "João Sá"
}
```

The httpbin response will include this instead:
```
{
  ...
  "json": null,
  ...
}
```

Testing this same experiment with `curl` does not reproduce the problem (the JSON is successfully parsed and shows up as expected in the httpbin response):

```
$ curl -X PUT http://httpbin.org/put -H "Content-Type: application/json" -d '{"text": "João Sá"}'
{
  ...
  "json": {
    "text": "Jo\u00e3o S\u00e1"
  }, 
  ...
}
```

**Comment by pashky** [comment]
I'm really surprised first example worked for you. In my tests both failed. 
Try updating, I've added utf-8 encoding. Seems to work here, but I really wonder what else I might have broken by this change.

**Comment by pandeiro** [comment]
Thanks @pashky; the version I have now from melpa is `restclient-20150309.707` but it still displays the same behavior described above.

**Comment by pashky** [comment]
Melpa? Are you kidding? I've updated it here, like, an hour ago!

**Comment by pandeiro** [comment]
I'm getting pretty tired of Melpa's slow release cycle...

**Comment by pandeiro** [comment]
Finally, Melpa!

Tested and it works:
```
{
  ...
  "json": {
    "text": "João Sá"
  },
  ...
}
```

:+1: -- thanks again!
