### ISSUE TITLE
POST hangs when a 201 Created is returned

### ISSUE THREAD

**Issue by timjstewart** [pashky/restclient.el#69]
restclient is the ultimate way of exploring REST APIs.  I love it.  I ran into a small problem and don't want to have to go to another tool even for a little bit.

I tried to pick up edebug to debug the problem but it was taking me too long.  May revisit when I get a chance.

I'm exploring the creation of a resource via a REST API.  When the API creates a resource, you get a 201 status code and the location of the new resource in a response header.

Here are the contents of my *HTTP Response* Buffer:

HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location
Date: Fri, 20 Mar 2015 21:31:15 GMT
Location: http://host/workflow/9035bfbd-e32e-1322-acd2-823c257ab1f1
Server: Apache-Coyote/1.1
Content-Length: 0
Connection: keep-alive

Here are the contents of my *URL-DEBUG* buffer:

http -> Found existing connection: host:80 #<process host>
http -> Reusing existing connection: host:80
http -> Marking connection as busy: host:80 #<process host>
http -> Request is: 
POST /workflow HTTP/1.1
MIME-Version: 1.0
Connection: keep-alive
Extension: Security/Digest Security/SSL
Host: host
Accept: */*
Content-Type: application/json
Content-length: 414

{
  "name": "Test Workflow",
  "description": "The first workflow, created while following the tutorials"
}
http -> Calling after change function `url-http-wait-for-headers-change-function' for `#<process host>'
http -> url-http-wait-for-headers-change-function ( *http host:80*-873342)
http -> Saw end of headers... ( *http host:80*-873342)
http -> url-http-parse-response called in ( *http host:80*-873342)
http -> Got a content-length, being smart about document end.
http -> Got 0-length content-length, activating callback immediately.
http -> Marking connection as free: host:80 #<process host>
http -> url-http-parse-headers called in ( *http host:80*-873342)
http -> url-http-parse-response called in ( *http host:80*-873342)
http -> Parsed HTTP headers: class=2 status=201
http -> Finished parsing HTTP headers: t
http -> Marking connection as free: host:80 #<process host>
http -> Activating callback in buffer ( *http host:80*-873342): restclient-http-handle-response (nil "POST" "http://host/gambit/api/workflow" "*HTTP Response*" nil nil)

So it calls the restclient-http-handle-response but there is where I start losing sight of the problem.

My theory is that because of the minimalistic response from the server, that in the while loop in restclient-prettify-response it's not seeing something it's expecting.  "^\\s-*$" perhaps?  And because of that, it's just looping forever.   In my minibuffer, I just get a Contacting host message that doesn't go away unless I C-g a number of times.

Thanks!

Could be related to Issue: https://github.com/pashky/restclient.el/issues/67

**Comment by timjstewart** [comment]
Did a little printf debugging of restclient-prettify-response:

Here's the second while loop:

      (while (looking-at "^\\s-*$")
        (message "E")
        (forward-line))

Here's an excerpt from my Messages buffer:

E [150868 times]

**Comment by timjstewart** [comment]
Changing 2nd loop to this fixed the hang, but I'm sure it's not the correct fix since it doesn't make any of the headers pretty:

      (while (and (looking-at "^\\s-*$")
                  (not (= (point) (point-max))))
        (message "E")
        (forward-line))

**Comment by timjstewart** [comment]
Ah, it's unable to guess the mode because there's no Content-Type in the response headers so all the prettification code is skipped.  Maybe that's as pretty as it needs to be?  This will suit my needs for the time being so I can get back to exploring the API.  If the meager snippets I've posted are worth a PR, please let me know.  I'll take out the calls to (message).  Thanks!

**Comment by pashky** [comment]
Wow, good find. This might be reason of that windows guy's problem. I tried to clean this part a bit, but I don't have service returning such response at hand and I'm too lazy to put up one :) Could you please test it and let me know?

**Comment by timjstewart** [comment]
Pavel, I reinstalled the latest version (20150323.259) and can no longer reproduce the hang.  I hope this helps Greg Lucas with his Windows problem.  Thanks for such a speedy reply and for an awesome tool!
