### ISSUE TITLE
Failed to parse JSON string in which 4 numbers follow a unicode character

### ISSUE THREAD

**Issue by hkurokawa** [pashky/restclient.el#80]
If an API returns a response containing a string, in which a 4 numbers follow a unicode character, such like "題1000" ("\u984c1000"), restclient failed to parse the response with `C-c C-c`.

#### Steps to reproduce
1. Upload a file of which content is
    
    ```
    "\u984c1000"
    ```
   to any public site.
2. Create a file as below and press `C-c C-c` on the line.
    
    ```
GET <URL of the uploaded file>
```

**Comment by pashky** [comment]
merged, thanks!
