### ISSUE TITLE
Whitespace handling in HTTP in entities

### ISSUE THREAD

**Issue by Astrac** [pashky/restclient.el#81]
I noticed that the rest client attaches some extra whitespace in the HTTP entity it sends, regardless of what method is being used in the request. In my case, when working with a particularly strict server, I can't test GET or HEAD requests as they are not supposed to have any body; we could argue that that is not necessarily true in the HTTP specification, but in some cases it is just good to have more control on this aspect. 

I also found this PR which looked abandoned and can't easily be merged as far as I can tell: https://github.com/pashky/restclient.el/pull/22

If I issue a new PR to trim the HTTP entity before sending the request will it be merged?

**Comment by pashky** [comment]
That PR is obsolete anyway. This issue was fixed some time ago, but apparently fix isn't working for empty body requests. I'll have a look later.
