### ISSUE TITLE
restclient-jump-next not working

### ISSUE THREAD

**Issue by glucas** [pashky/restclient.el#89]
The command `restclient-jump-next` (bound to `C-c C-n`) does not move point. The corresponding command `restclient-jump-prev` (bound to `C-c C-p`) works as expected in the same buffer.

Testing with Emacs 24.4 -Q on Windows 8.1, with restclient 20150818.807. (Also tried on a recent Emacs 25 snapshot.)
.

**Comment by senarukana** [comment]
Hey, I face the same problem on Mac 10.10.5. Have you solved it?

**Comment by glucas** [comment]
@senarukana Not yet, but I see when it broke so perhaps I can submit a pull request. 

The commit a9254c30d914b0e79cca55c0b6261278b6f8da99 changed the implementation of `restclient-current-max` in a way that breaks `restclient-jump-next`.

**Comment by pashky** [comment]
Thanks Greg. I've fixed further minor issue happening when you're at the end of buffer and last thing there is #

**Comment by glucas** [comment]
Thanks - this is working great for me.
