### ISSUE TITLE
No way to prevent results window from popping up

### ISSUE THREAD

**Issue by alf** [pashky/restclient.el#90]
I'm integrating restclient with org-mode and have something that's good enough for me except for one little annoyance: the results window pops up. I've found no good way to disable this.

**Comment by pashky** [comment]
What'd you prefer to happen to results then? 
You should see end of restclient-http-handle-response function. There's a display-buffer call you can adjust to set your own behaviour.

**Comment by alf** [comment]
Here's my current (minimal) ob-restclient code:

```elisp
(defun org-babel-execute:restclient (body params)
  "Execute a block of Restclient code with org-babel.
This function is called by `org-babel-execute-src-block'"
  (message "executing Restclient source code block")
  (save-window-excursion
    (with-temp-buffer
      (insert body)
      (restclient-http-send-current-stay-in-window))
    (with-current-buffer restclient-same-buffer-response-name
      (goto-char (point-min))
      (insert "#+BEGIN_SRC html\n")
      (goto-char (point-max))
      (insert "#+END_SRC\n")
      (buffer-string))))
```
Since I'm showing it inline in the org-mode buffer, having the result window is redundant and annoying. Unfortunately (probably related to my limited understanding of elisp) I find no way to prevent the window with the result from popping up.

The above code also depends on restclient-same-buffer-response being t. If it's nil, the code breaks.

Ideally, I'd like to get the result buffer as the result value from restclient-http-send-current-stay-in-window, and some way to prevent that buffer from being displayed.

**Comment by pashky** [comment]
(restclient-http-parse-current-and-do 'restclient-http-do ...args...) call will pass those args all the way down to restclient-http-handle-response, where you can make (display-buffer) conditional or even pass a callback function there, so one will return response text for your case or another one will display a buffer.

**Comment by alf** [comment]
Just to be sure I understand you last comment.

You're saying that I can modify `restclient-http-handle-response` to take extra arguments that will allow me to do what I'm asking.

Is this a change you'll be interested in merging if done properly?

**Comment by alf** [comment]
I've made an attempt at #91. Please feel free to reject it and suggest improvements.

**Comment by alf** [comment]
After reading the manual for display-buffer I no longer believe this bug is relevant. I'm able to use dynamic binding to make restclient behave as I want.
