### ISSUE TITLE
POST doesn't work

### ISSUE THREAD

**Issue by caijq4ever** [pashky/restclient.el#98]
There is a problem about http post
```elisp
POST http://www.example.com/testpost.php
{"name":"Junqi"}
```

And testpost.php code is here:
```php
<?php
echo $_POST['name'];
```
But the response doesn't return the value of name.It's Undefined.

**Comment by zarkone** [comment]
:+1:

**Comment by pashky** [comment]
I've never worked with PHP, but are you guys sure it parses JSON payload like that?

**Comment by zarkone** [comment]
I'm working with clojure backend, examples from README do not pass the
params with POST. simular curl command works for that server. If i'll
investigate why, i'll report and PR

pashky writes:

**Comment by zarkone** [comment]
lol, i'm stupid -- it's json payload while we parse http params

**Comment by pashky** [comment]
https://en.wikipedia.org/wiki/POST_(HTTP)#Use_for_submitting_web_forms
You need to use URL encoded POST body in restclient.el

**Comment by zarkone** [comment]
yes, sorry >..<

**Comment by caijq4ever** [comment]
@pashky 
>  I've never worked with PHP, but are you guys sure it parses JSON payload like that?

Yes.
I tried many times. PHP just prints the result of POST data.
And the same as worked with JAVA.
Can you show me a demo? (:

**Comment by zarkone** [comment]
Are you sure?
http://stackoverflow.com/questions/9597052/how-to-retrieve-request-payload

2015-10-08 8:44 GMT+06:00 Junqi Cai <notifications@github.com>:

**Comment by caijq4ever** [comment]
testpost.restclient(*client*):
```elisp
POST http://114.255.216.92/testpost.php
Content-Type: application/x-www-form-urlencoded
{"name": "caijunqi"}
```

And testpost.php(*server*):
```php
<?php
echo file_get_contents('php://input') . PHP_EOL;
echo $_POST['name'];
```

curl like this:
```shell
$ curl -i -H '{"name": "caijunqi"}' -H 'Content-Type: application/x-www-form-urlencoded' -XPOST 'http://114.255.216.92/testpost.php'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   110  100   110    0     0    470      0 --:--:-- --:--:-- --:--:--   470HTTP/1.1 200 OK
Date: Thu, 08 Oct 2015 09:54:49 GMT
Server: Apache/2.4.9 (Unix) PHP/5.5.10
X-Powered-By: PHP/5.5.10
Content-Length: 110
Content-Type: text/html


<br />
<b>Notice</b>:  Undefined index: name in <b>/var/wwwroot/html/testpost.php</b> on line <b>3</b><br />
```
@pashky  @zarkone

**Comment by pashky** [comment]
Come on man, go learn how to HTTP already. 
{"name": "caijunqi"} is NOT properly URL-encoded string.

**Comment by caijq4ever** [comment]
##### I see.Thx.

**Comment by shakdwipeea** [comment]
for anyone who stumble here: https://stackoverflow.com/questions/14551194/how-are-parameters-sent-in-an-http-post-request
